+ Medium API implementation, resolves #9
rusiruavb/portfolio-api pull request #12
Opened 2021-06-09 18:23 UTC by rustmn

There is no way to retrieve Medium posts via their API. Method, described in PR, retrieves RSS-feed which contain blog posts and convert them into JSON.

2021-06-09 19:21 UTC, rusiruavb requested changes
Could you please do the changes that I have mention. Others are LGTM

2021-06-09 19:21 UTC, rusiruavb commented on src/controller/user.controller.ts
> +import { insertUser, getUserById, getUserDetails, updateUserbyId, checkUserByUsernameAndPassword, getUserMediumPosts } from '../service/user.service';
@rustmn brother, these functions should be in a separate file.
for example, this is for getting Medium posts. So,  it should in a separate file called `medium.controller.ts`

2021-06-09 19:21 UTC, rusiruavb commented on src/routes.ts
> +import { createUser, loginUser, getUserAccount, getPublicUserAccount, updateUser, getMediumPosts } from './controller/user.controller';
get this `getMediumPosts` from that separate file that I have mention above

2021-06-09 19:21 UTC, rusiruavb commented
@rustmn Create a separate feature branch by the way.
example: `feature/medium`

2021-06-09 19:23 UTC, rusiruavb commented
And also, make the PR to development branch

2021-06-10 04:50 UTC, merged

2021-06-10 05:54 UTC, rustmn commented
@rusiruavb, sorry, but I haven't enough time right now, I'll look here as I'm free.

2021-06-10 06:01 UTC, rusiruavb commented
> @rusiruavb, sorry, but I haven't enough time right now, I'll look here as I'm free.

Ah.. it's fine @rustmn . Actually, thank you for solving my problem. 😍❤